<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQSGiJ6O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQSGiJ6O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQSGiJ6O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQSGiJ6O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQSGiJ6O\App_KernelDevDebugContainer([
    'container.build_hash' => 'QSGiJ6O',
    'container.build_id' => '08bb7fc1',
    'container.build_time' => 1623102375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQSGiJ6O');
